# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.5.3-bb.0
appVersion: 1.0.10
annotations:
  bigbang.dev/applicationVersions: |
    - backstage: 1.0.10
  bigbang.dev/upstreamReleaseNotesMarkdown: |
    The [upstream chart's release notes](https://github.com/backstage/charts/releases) may help when reviewing this package.
  helm.sh/images: |
    - name: backstage
      image: registry1.dso.mil/ironbank/big-bang/backstage:1.0.10
    - name: base
      image: registry1.dso.mil/ironbank/big-bang/base:2.1.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: support
      url: https://github.com/backstage/charts/issues
    - name: Chart Source
      url: https://github.com/backstage/charts
    - name: Default Image Source
      url: https://github.com/backstage/backstage
apiVersion: v2
description: A Helm chart for deploying a Backstage application
dependencies:
  - name: backstage
    repository: oci://ghcr.io/backstage/charts
    tags:
      - 2.5.3
    version: 2.5.3
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.10.0
  - name: gluon
    version: "0.6.3"
    repository: "oci://registry1.dso.mil/bigbang"
home: https://backstage.io
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/backstage/icon/color/backstage-icon-color.svg
keywords:
  - backstage
  - idp
kubeVersion: ">= 1.19.0-0"
maintainers:
  - name: Backstage
    url: https://backstage.io
name: backstage
type: application
sources:
  - https://github.com/backstage/charts
  - https://github.com/backstage/backstage
