# Backstage override configuration for your local development environment
app:
  baseUrl: http://localhost:7007

auth:
  environment: development
  providers: 
    guest:
      # because we use NODE_ENV: production, we must set this to allow guest development login
      dangerouslyAllowOutsideDevelopment: true
    github:
      development:
        clientId: 'replaceme'
        clientSecret: 'replaceme'
        signIn:
          resolvers:
            # Matches the Github username with the Backstage user entity name
            # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers.
            - resolver: usernameMatchingUserEntityName

proxy:
  '/grafana/api':
    # May be a public or an internal DNS
    target: ${GRAFANA_HTTP}://${GRAFANA_URL}
    headers:
      Authorization: Bearer ${GRAFANA_TOKEN}

grafana:
  # Publicly accessible domain
  domain: ${GRAFANA_DOMAIN}

  # Is unified alerting enabled in Grafana?
  # See: https://grafana.com/blog/2021/06/14/the-new-unified-alerting-system-for-grafana-everything-you-need-to-know/
  # Optional. Default: false
  unifiedAlerting: false

kubernetes:
  customResources:
    - group: 'networking.istio.io'
      apiVersion: 'v1'
      plural: 'virtualservices'
    - group: 'networking.k8s.io'
      apiVersion: 'v1'
      plural: 'networkpolicies'
    - group: 'security.istio.io'
      apiVersion: 'v1'
      plural: 'authorizationpolicies'
    - group: 'security.istio.io'
      apiVersion: 'v1'
      plural: 'peerauthentications'
    - group: 'source.toolkit.fluxcd.io'
      apiVersion: 'v1'
      plural: 'helmcharts'
    - group: 'helm.toolkit.fluxcd.io'
      apiVersion: 'v2'
      plural: 'helmreleases'
    - group: 'source.toolkit.fluxcd.io'
      apiVersion: 'v1'
      plural: 'gitrepositories'
    - group: 'wgpolicyk8s.io'
      apiVersion: 'v1alpha2'
      plural: 'clusterpolicyreports'
    - group: 'wgpolicyk8s.io'
      apiVersion: 'v1alpha2'
      plural: 'policyreports'
    - group: 'kyverno.io'
      apiVersion: 'v1'
      plural: 'clusterpolicies'
  frontend:
    podDelete:
      enabled: true
  serviceLocatorMethod:
    type: 'multiTenant'
  clusterLocatorMethods:
    - type: 'config'
      clusters:
        - url: http://127.0.0.1:9999
          name: bigbang-dev
          authProvider: 'serviceAccount'
          skipTLSVerify: false
          skipMetricsLookup: true

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml

    - type: file
      target: ./examples/template/template.yaml

    # local example organizational data
    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]
