{{- if and .Values.istio.enabled .Values.istio.hardened.enabled -}}
{{- range .Values.istio.backstage.gateways -}}
{{- $namespace := $.Values.istio.namespace -}}
{{- $name := . -}}
{{- if contains "/" $name -}}
{{- $gatewayParts := split "/" $name }}
{{- $namespace = $gatewayParts._0 -}}
{{- $name = $gatewayParts._1 -}}
{{- end -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "common.names.fullname" $ }}-ingressgateway-authz-policy
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: backstage
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces:
        - {{ $namespace }}
        principals:
        - "cluster.local/ns/{{ $namespace }}/sa/{{ $name }}-ingressgateway-service-account"
---
{{ end -}}
{{- end }}

