{{- if .Values.backstage.backstage.initContainers }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-grafana-secret
  annotations:
    policies.kyverno.io/title: sync grafana admin defaultt
    policies.kyverno.io/category: backstage
    policies.kyverno.io/subject: grafana default admin
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  background: false
  validationFailureAction: Enforce
  rules:
  - name: sync-grafana-credentials-backstage
    match:
      resources:
        kinds:
          - Namespace
        selector:
          matchLabels:
            kubernetes.io/metadata.name: {{ .Release.Namespace }}
    generate:
      apiVersion: v1
      kind: Secret
      name: monitoring-grafana
      namespace: {{ .Release.Namespace }}
      synchronize: true
      generateExisting: true
      clone:
        namespace: monitoring
        name: monitoring-grafana
{{- end }}
