---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: applications
spec:
  owner: guests
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-system
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: security
spec:
  owner: platform-team
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: base-deployment
  annotations:
    grafana/dashboard-selector: "(tags @> 'my-service' || tags @> 'Policy Reporter')"
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/managed-by=Helm'
spec:
  type: website
  lifecycle: production
  owner: guests
  system: applications
  providesApis: [k8s-grpc-api]

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kyverno-policy
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=kyverno-policies'
spec:
  type: website
  lifecycle: production
  owner: platform-team
  system: security
  providesApis: [kyverno-policy-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: k8s-grpc-api
spec:
  type: grpc
  lifecycle: production
  owner: guests
  system: applications
  definition: |
    syntax = "proto3";

    service Exampler {
      rpc Example (ExampleMessage) returns (ExampleMessage) {};
    }

    message ExampleMessage {
      string example = 1;
    };

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: kyverno-policy-api
  description: API for interacting with Kyverno policies.
spec:
  type: policy
  lifecycle: production
  owner: platform-team
  system: security
  definition: |
    swagger: "2.0"
    info:
      title: Kyverno Policy API
      version: "1.0.0"
    paths:
      /policies:
        get:
          summary: List all Kyverno policies
          responses:
            "200":
              description: A list of Kyverno policies.
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                    spec:
                      type: object
        post:
          summary: Create a new Kyverno policy
          parameters:
            - in: body
              name: policy
              description: The Kyverno policy to create.
              required: true
              schema:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  metadata:
                    type: object
                  spec:
                    type: object
          responses:
            "201":
              description: The created Kyverno policy.
      /policies/{name}:
        get:
          summary: Get a Kyverno policy by name
          parameters:
            - in: path
              name: name
              required: true
              type: string
              description: The name of the Kyverno policy.
          responses:
            "200":
              description: The Kyverno policy.
              schema:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  spec:
                    type: object
        delete:
          summary: Delete a Kyverno policy by name
          parameters:
            - in: path
              name: name
              required: true
              type: string
              description: The name of the Kyverno policy.
          responses:
            "204":
              description: Kyverno policy deleted.