{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backstage
    app.kubernetes.io/part-of: {{ include "common.names.fullname" . }}
spec:
  gateways:
  {{- range .Values.istio.backstage.gateways }}
    - {{ . }}
  {{- end }}
  hosts:
  {{- range .Values.istio.backstage.hosts }}
    - {{ tpl . $}}
  {{- end }}
  http:
  - route:
    - destination:
        port:
          number: {{ .Values.service.ports.backend }}
        host: {{ include "common.names.fullname" . }}.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
{{- end }}
