apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: backstage
  labels:
    {{- include "app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage
subjects:
  - kind: ServiceAccount
    name: backstage
    namespace: {{ .Release.Namespace }}
