apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Release.Namespace }}
  name: backstage
  labels:
    {{- include "app.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - resourcequotas
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - create
      - patch
      - update
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - 'networking.istio.io'
      - 'security.istio.io'
      - 'source.toolkit.fluxcd.io'
      - 'helm.toolkit.fluxcd.io'
      - 'networking.k8s.io'
      - 'wgpolicyk8s.io'
      - 'kyverno.io'
    resources:
      - virtualservices
      - networkpolicies
      - authorizationpolicies
      - peerauthentications
      - helmcharts
      - helmreleases
      - gitrepositories
      - policyreports
      - clusterpolicyreports 
      - clusterpolicies
    verbs:
      - get
      - list
      - watch
